#Assignment code :

Create one 4*4 2D array.

Create one 1D array having length 4 and add that array to 2d array by rowwise broadcasting

CONVERT THE ROW ARRAY TO COLUMN ARRAY.

Multiply the column array on 2d array by column wise broadcasting.

In [2]:
import numpy as np

In [3]:
arr = np.array([[4,6,8,1],[5,1,8,2],[9,5,2,1],[6,8,0,1]])
print(arr)

[[4 6 8 1]
 [5 1 8 2]
 [9 5 2 1]
 [6 8 0 1]]


In [4]:
arr2 = np.array([10,20,30,40])
print(arr2)

arr = arr + arr2

arr3 = arr2.reshape(-1,1)

print(arr * arr3)

#Pandas

In [12]:
! pip install pandas

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [13]:
import pandas as pd

In [14]:
df = pd.read_csv('diamonds.csv')

In [15]:
df

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0               1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1               2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2               3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3               4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4               5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
...           ...    ...        ...   ...     ...    ...    ...    ...   ...   
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75   
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69   
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66   
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15   
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83   

          y     z  
0      3.98  2.43  
1      3.84  2.31  
2      4.07  2.31  
3      4.23  2.63  
4      4.35  2.75  
...     ...   ...  
53935  5.76  3.50  
53936  5.75  3.61  
53937  5.68  3.56  
53938  6.12  3.74  
53939  5.87  3.64  

[53940 rows x 11 columns]

In [16]:
df.head()

Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  
0  2.43  
1  2.31  
2  2.31  
3  2.63  
4  2.75

In [17]:
df.tail()

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
53935       53936   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75   
53936       53937   0.72       Good     D     SI1   63.1   55.0   2757  5.69   
53937       53938   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66   
53938       53939   0.86    Premium     H     SI2   61.0   58.0   2757  6.15   
53939       53940   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83   

          y     z  
53935  5.76  3.50  
53936  5.75  3.61  
53937  5.68  3.56  
53938  6.12  3.74  
53939  5.87  3.64

In [18]:
df.head(15)

Unnamed: 0  carat        cut color clarity  depth  table  price     x  \
0            1   0.23      Ideal     E     SI2   61.5   55.0    326  3.95   
1            2   0.21    Premium     E     SI1   59.8   61.0    326  3.89   
2            3   0.23       Good     E     VS1   56.9   65.0    327  4.05   
3            4   0.29    Premium     I     VS2   62.4   58.0    334  4.20   
4            5   0.31       Good     J     SI2   63.3   58.0    335  4.34   
5            6   0.24  Very Good     J    VVS2   62.8   57.0    336  3.94   
6            7   0.24  Very Good     I    VVS1   62.3   57.0    336  3.95   
7            8   0.26  Very Good     H     SI1   61.9   55.0    337  4.07   
8            9   0.22       Fair     E     VS2   65.1   61.0    337  3.87   
9           10   0.23  Very Good     H     VS1   59.4   61.0    338  4.00   
10          11   0.30       Good     J     SI1   64.0   55.0    339  4.25   
11          12   0.23      Ideal     J     VS1   62.8   56.0    340  3.93   
12          13   0.22    Premium     F     SI1   60.4   61.0    342  3.88   
13          14   0.31      Ideal     J     SI2   62.2   54.0    344  4.35   
14          15   0.20    Premium     E     SI2   60.2   62.0    345  3.79   

       y     z  
0   3.98  2.43  
1   3.84  2.31  
2   4.07  2.31  
3   4.23  2.63  
4   4.35  2.75  
5   3.96  2.48  
6   3.98  2.47  
7   4.11  2.53  
8   3.78  2.49  
9   4.05  2.39  
10  4.28  2.73  
11  3.90  2.46  
12  3.84  2.33  
13  4.37  2.71  
14  3.75  2.27

In [21]:
l = list(df.columns)

In [22]:
l

['Unnamed: 0',
 'carat',
 'cut',
 'color',
 'clarity',
 'depth',
 'table',
 'price',
 'x',
 'y',
 'z']

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 53940 entries, 0 to 53939
Data columns (total 11 columns):
 #   Column      Non-Null Count  Dtype  
---  ------      --------------  -----  
 0   Unnamed: 0  53940 non-null  int64  
 1   carat       53940 non-null  float64
 2   cut         53940 non-null  object 
 3   color       53940 non-null  object 
 4   clarity     53940 non-null  object 
 5   depth       53940 non-null  float64
 6   table       53940 non-null  float64
 7   price       53940 non-null  int64  
 8   x           53940 non-null  float64
 9   y           53940 non-null  float64
 10  z           53940 non-null  float64
dtypes: float64(6), int64(2), object(3)
memory usage: 4.5+ MB


In [25]:
df.head()

Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  
0  2.43  
1  2.31  
2  2.31  
3  2.63  
4  2.75

#Column based Slicing of dataframe

In [28]:
df['color']

0        E
1        E
2        E
3        I
4        J
        ..
53935    D
53936    D
53937    D
53938    H
53939    D
Name: color, Length: 53940, dtype: object

In [30]:
x = df[['cut','color','table']]

#Condition based slicing(filtering)

In [32]:
df.head()

Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  
0  2.43  
1  2.31  
2  2.31  
3  2.63  
4  2.75

In [33]:
df[df['cut'] == 'Good']

Unnamed: 0  carat   cut color clarity  depth  table  price     x     y  \
2               3   0.23  Good     E     VS1   56.9   65.0    327  4.05  4.07   
4               5   0.31  Good     J     SI2   63.3   58.0    335  4.34  4.35   
10             11   0.30  Good     J     SI1   64.0   55.0    339  4.25  4.28   
17             18   0.30  Good     J     SI1   63.4   54.0    351  4.23  4.29   
18             19   0.30  Good     J     SI1   63.8   56.0    351  4.23  4.26   
...           ...    ...   ...   ...     ...    ...    ...    ...   ...   ...   
53913       53914   0.80  Good     G     VS2   64.2   58.0   2753  5.84  5.81   
53914       53915   0.84  Good     I     VS1   63.7   59.0   2753  5.94  5.90   
53916       53917   0.74  Good     D     SI1   63.1   59.0   2753  5.71  5.74   
53927       53928   0.79  Good     F     SI1   58.1   59.0   2756  6.06  6.13   
53936       53937   0.72  Good     D     SI1   63.1   55.0   2757  5.69  5.75   

          z  
2      2.31  
4      2.75  
10     2.73  
17     2.70  
18     2.71  
...     ...  
53913  3.74  
53914  3.77  
53916  3.61  
53927  3.54  
53936  3.61  

[4906 rows x 11 columns]

In [40]:
x = df[(df['cut'] == 'Good') & (df['color']=='J')]
x[['table','price','depth']]

#Alternate way
df[(df['cut'] == 'Good') & (df['color']=='J')][['table','price','depth']]

In [ ]:
# 'carat' should be more than 0.5 and cut should be 'Good'. 
#Select price for the filtered data

In [49]:
df[(df['carat']>0.5) & (df['cut']=='Good')]['price']

95       2759
96       2759
145      2767
169      2772
175      2774
         ... 
53913    2753
53914    2753
53916    2753
53927    2756
53936    2757
Name: price, Length: 3522, dtype: int64

#Numerical computations on dataframe

In [52]:
df['price'].mean()

3932.799721913237

In [53]:
df['price'].min()

326

In [54]:
df['price'].max()

18823

In [55]:
df['price'].std()

3989.439738146379

In [57]:
df.head()

Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  
0  2.43  
1  2.31  
2  2.31  
3  2.63  
4  2.75

In [61]:
# Find the average price of diamonds with 'Premium' cut.
df[df['cut']=='Premium']['price'].min() , df[df['cut']=='Premium']['price'].max()

(326, 18823)

In [62]:
#Select row having maximum price
x = df['price'].max()
df[df['price'] ==x ]

Unnamed: 0  carat      cut color clarity  depth  table  price    x  \
27749       27750   2.29  Premium     I     VS2   60.8   60.0  18823  8.5   

          y     z  
27749  8.47  5.16

In [ ]:
#Alternative way
df[df['price'] == df['price'].max()]

#Operation between 2 columns

In [63]:
df['New_column'] = df['x'] + df['y'] + df['z']

In [64]:
df.head()

Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  New_column  
0  2.43       10.36  
1  2.31       10.04  
2  2.31       10.43  
3  2.63       11.06  
4  2.75       11.44

In [65]:
df['New_Concated_Column'] = df['cut']+ "___" + df["color"] + df["clarity"]

In [66]:
df.head()

Unnamed: 0  carat      cut color clarity  depth  table  price     x     y  \
0           1   0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98   
1           2   0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84   
2           3   0.23     Good     E     VS1   56.9   65.0    327  4.05  4.07   
3           4   0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23   
4           5   0.31     Good     J     SI2   63.3   58.0    335  4.34  4.35   

      z  New_column New_Concated_Column  
0  2.43       10.36        Ideal___ESI2  
1  2.31       10.04      Premium___ESI1  
2  2.31       10.43         Good___EVS1  
3  2.63       11.06      Premium___IVS2  
4  2.75       11.44         Good___JSI2

# Assignment code 

Read excel file as pandas dataframe which contains multiple sheets

Store all the sheet data in different dataframes
