#Numpy

Numerical + python

In [3]:
import numpy as np

In [4]:
l = [3,5,8,3,2]

In [6]:
arr = np.array([4,3,5,6,8])

In [7]:
print(arr)

[4 3 5 6 8]


In [8]:
print(l)

[3, 5, 8, 3, 2]


In [9]:
arr_2d = np.array([[5,2,7],[8,1,2]])

In [10]:
print(arr_2d)

[[5 2 7]
 [8 1 2]]


#Check characteristics of array

In [41]:
arr = np.array([[5,2,7],[8,1,2]])

In [43]:
#Dimension of array
op = arr.ndim
print(op)

2


In [44]:
#Shape of array
op2 = arr.shape

In [45]:
print(op2)

(2, 3)


In [14]:
#datatype of elements
arr.dtype

dtype('int64')

#Create array based on requirements

In [15]:
arr1 = np.array([[5,2,7],[8,1,2]])

In [22]:
arr4 = np.ones(6)
arr4

array([1., 1., 1., 1., 1., 1.])

In [16]:
#Create array with zeros
arr2 = np.zeros((2,5))

In [18]:
#Create array with ones
arr3 = np.ones((3,6))

In [23]:
#Create array for any value
arr5 = np.full((4,7),25)

In [24]:
arr5

array([[25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25, 25]])

In [32]:
#Create array with range
arr6 = np.arange(0,30,4)

#Array slicing

In [47]:
arr = np.array([[4,2,8,9],[5,1,0,9],[4,1,6,9],[6,1,0,0]])

In [35]:
print(arr)

[[4 2 8 9]
 [5 1 0 9]
 [4 1 6 9]
 [6 1 0 0]]


In [36]:
arr[2,2]

6

In [37]:
arr[0:2,:]

array([[4, 2, 8, 9],
       [5, 1, 0, 9]])

In [38]:
#First row
arr[ 0, :]

array([4, 2, 8, 9])

In [39]:
#Last column
arr[ : ,3]

array([9, 9, 9, 0])

In [48]:
#First 3 rows and 3 columns
arr[0:3,0:3]

array([[4, 2, 8],
       [5, 1, 0],
       [4, 1, 6]])

In [49]:
# Last 2 columns
arr[:,2:]

array([[8, 9],
       [0, 9],
       [6, 9],
       [0, 0]])

#Array flattening

In [53]:
arr = np.array([[4,2,8,9],[5,1,0,9],[4,1,6,9],[6,1,0,0]])

In [54]:
print(arr)
print(arr.shape)

[[4 2 8 9]
 [5 1 0 9]
 [4 1 6 9]
 [6 1 0 0]]
(4, 4)


In [51]:
x = arr.flatten()

In [52]:
print(x)

[4 2 8 9 5 1 0 9 4 1 6 9 6 1 0 0]


#Array reshaping

In [59]:
arr2 = arr.reshape((2,8))
print(arr2)

[[4 2 8 9 5 1 0 9]
 [4 1 6 9 6 1 0 0]]


In [60]:
arr3 = arr.reshape((8,2))
print(arr3)

[[4 2]
 [8 9]
 [5 1]
 [0 9]
 [4 1]
 [6 9]
 [6 1]
 [0 0]]


In [62]:
#This will generate error
arr4 = arr.reshape((5,3))
print(arr4)

In [64]:
arr5 = arr.reshape((1,16))
print(arr5)

[[4 2 8 9 5 1 0 9 4 1 6 9 6 1 0 0]]


#Practice code

Create 1 numpy array having dimension 4,5 and values are 1

Create 1 numpy array having dimension 4,5 and values are 45

Check their dimension and shape, If dimensions and shape of both arrays are same, print : "They both can do mathemeticaloperations"

In [25]:
arr1 = np.ones((4,5))

In [26]:
arr1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [27]:
arr2 = np.full((4,5),45)

In [28]:
arr2

array([[45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45],
       [45, 45, 45, 45, 45]])

In [29]:
if(arr1.ndim == arr2.ndim and arr1.shape == arr2.shape):
  print("They both can do mathemeticaloperations")

They both can do mathemeticaloperations
