In [ ]:
import numpy as np

In [ ]:
arr = np.array([3,5,7,1,4,2,5])

In [ ]:
np.sum(arr)

27

In [ ]:
np.mean(arr), np.median(arr)

(3.857142857142857, 4.0)

In [ ]:
np.sin(arr), np.cos(arr)

(array([ 0.14112001, -0.95892427,  0.6569866 ,  0.84147098, -0.7568025 ,
         0.90929743, -0.95892427]),
 array([-0.9899925 ,  0.28366219,  0.75390225,  0.54030231, -0.65364362,
        -0.41614684,  0.28366219]))

In [ ]:
np.min(arr), np.max(arr)

1

#Numerical operations on 2D array

In [ ]:
arr = np.array([[2,4,1,7],[5,2,7,1],[3,6,1,0],[5,4,3,2]])
print(arr)

[[2 4 1 7]
 [5 2 7 1]
 [3 6 1 0]
 [5 4 3 2]]


In [ ]:
np.max(arr), np.min(arr)

(7, 0)

In [ ]:
np.max(arr, axis = 0)
#Column wise operation

array([5, 6, 7, 7])

In [ ]:
np.max(arr , axis = 1)
#Row wise operation

array([7, 7, 6, 5])

In [ ]:
np.mean(arr, axis = 1)

array([3.5 , 3.75, 2.5 , 3.5 ])

In [ ]:
np.sum(arr, axis = 1)

array([14, 15, 10, 14])

In [ ]:
arr = np.array([[2,4,1,7],[5,2,7,1],[3,6,1,0],[5,4,3,2]])
print(arr)

[[2 4 1 7]
 [5 2 7 1]
 [3 6 1 0]
 [5 4 3 2]]


In [ ]:
arr = arr + 10

In [ ]:
arr = arr * 10

In [ ]:
arr

array([[120, 140, 110, 170],
       [150, 120, 170, 110],
       [130, 160, 110, 100],
       [150, 140, 130, 120]])

In [ ]:
print(arr)

[[120 140 110 170]
 [150 120 170 110]
 [130 160 110 100]
 [150 140 130 120]]


In [ ]:
arr2 = np.array([[4,1,8,7],[8,3,9,4],[6,7,1,2],[6,4,3,1]])
print(arr2)

[[4 1 8 7]
 [8 3 9 4]
 [6 7 1 2]
 [6 4 3 1]]


In [ ]:
arr + arr2

array([[124, 141, 118, 177],
       [158, 123, 179, 114],
       [136, 167, 111, 102],
       [156, 144, 133, 121]])

#Practice code :

Create 2d array having shape 4*4

find columnwise minimum and store arrayvalue in l1

create 2d array with shape 4*4

find rowwise average and store arrayvalue in l2

Perform multiplication between l1 and l2

In [ ]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[1,2,3,5],[9,8,4,3]])

In [ ]:
l1 = np.min(arr1, axis =0)

In [ ]:
arr2=np.array([[2,3,4,5],[1,2,3,4],[3,4,5,6],[1,2,5,6]])

In [ ]:
l2 = np.mean(arr2, axis = 1)

In [ ]:
l1 * l2

array([ 3.5,  5. , 13.5, 10.5])

#Broadcasting in array

In [ ]:
arr1 = np.array([[1,2,3,4],[5,6,7,8],[1,2,3,5],[9,8,4,3]])
print(arr1)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 5]
 [9 8 4 3]]


In [ ]:
row_array = np.array([10,20,30,40])
arr1 + row_array

array([[11, 22, 33, 44],
       [15, 26, 37, 48],
       [11, 22, 33, 45],
       [19, 28, 34, 43]])

In [ ]:
col_array = np.array([[10],[20],[30],[40]])
print(col_array)

[[10]
 [20]
 [30]
 [40]]


In [ ]:
arr1 + col_array

array([[11, 12, 13, 14],
       [25, 26, 27, 28],
       [31, 32, 33, 35],
       [49, 48, 44, 43]])

#Assignment code :

Create one 4*4 2D array.

Create one 1D array having length 4 and add that array to 2d array by rowwise broadcasting

CONVERT THE ROW ARRAY TO COLUMN ARRAY.

Multiply the column array on 2d array by column wise broadcasting.

#Practice code

Create 2d array having shape 4*4

Find array that contains average of all columns

get the sum of that average array.

In [ ]:
arr = np.array([[2,4,1,7],[5,2,7,1],[3,6,1,0],[5,4,3,2]])
print(arr)

[[2 4 1 7]
 [5 2 7 1]
 [3 6 1 0]
 [5 4 3 2]]


In [ ]:
np.sum(np.mean(arr, axis = 0))

13.25